import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Booking, BookingStatus, JobType } from '@/types/booking';
import { toast } from 'sonner';

export function useBookings() {
  return useQuery({
    queryKey: ['bookings'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('bookings')
        .select('*')
        .order('event_date', { ascending: true });
      
      if (error) throw error;
      return data as Booking[];
    },
  });
}

export function useBooking(id: string | undefined) {
  return useQuery({
    queryKey: ['booking', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('bookings')
        .select('*')
        .eq('id', id)
        .single();
      
      if (error) throw error;
      return data as Booking;
    },
    enabled: !!id,
  });
}

interface CreateBookingData {
  client_name: string;
  client_phone?: string;
  client_email?: string;
  job_type: JobType;
  event_date: string;
  time_start?: string;
  time_end?: string;
  location?: string;
  total_price: number;
  deposit_amount: number;
  notes?: string;
  status?: BookingStatus;
}

export function useCreateBooking() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateBookingData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: booking, error } = await supabase
        .from('bookings')
        .insert({
          client_name: data.client_name,
          client_phone: data.client_phone || null,
          client_email: data.client_email || null,
          job_type: data.job_type,
          event_date: data.event_date,
          time_start: data.time_start || null,
          time_end: data.time_end || null,
          location: data.location || null,
          total_price: data.total_price,
          deposit_amount: data.deposit_amount,
          notes: data.notes || null,
          status: data.status || 'draft',
          user_id: user.id,
          booking_number: '', // Generated by trigger
        } as any)
        .select()
        .single();
      
      if (error) throw error;
      return booking as Booking;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
      toast.success('Booking created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create booking: ' + error.message);
    },
  });
}

export function useUpdateBooking() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<Booking> & { id: string }) => {
      const { data: booking, error } = await supabase
        .from('bookings')
        .update(data)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return booking as Booking;
    },
    onSuccess: (booking) => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
      queryClient.invalidateQueries({ queryKey: ['booking', booking.id] });
      toast.success('Booking updated successfully');
    },
    onError: (error) => {
      toast.error('Failed to update booking: ' + error.message);
    },
  });
}

export function useDeleteBooking() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('bookings')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
      toast.success('Booking deleted successfully');
    },
    onError: (error) => {
      toast.error('Failed to delete booking: ' + error.message);
    },
  });
}

export function useConfirmDeposit() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { data: booking, error } = await supabase
        .from('bookings')
        .update({
          status: 'booked' as BookingStatus,
          deposit_received_date: new Date().toISOString().split('T')[0],
        })
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return booking as Booking;
    },
    onSuccess: (booking) => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
      queryClient.invalidateQueries({ queryKey: ['booking', booking.id] });
      toast.success('Deposit confirmed! Booking is now confirmed.');
    },
    onError: (error) => {
      toast.error('Failed to confirm deposit: ' + error.message);
    },
  });
}
