import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Quotation, QuotationStatus } from '@/types/package';
import { JobType } from '@/types/booking';
import { toast } from 'sonner';

export function useQuotations() {
  return useQuery({
    queryKey: ['quotations'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('quotations')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Quotation[];
    },
  });
}

export function useQuotation(id: string | undefined) {
  return useQuery({
    queryKey: ['quotation', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('quotations')
        .select('*')
        .eq('id', id)
        .single();
      
      if (error) throw error;
      return data as Quotation;
    },
    enabled: !!id,
  });
}

interface CreateQuotationData {
  client_name: string;
  client_phone?: string;
  client_email?: string;
  client_note?: string;
  job_type: JobType;
  event_date?: string;
  time_start?: string;
  time_end?: string;
  location?: string;
  total_price: number;
  notes?: string;
  valid_until?: string;
  package_id?: string;
}

export function useCreateQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateQuotationData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: quotation, error } = await supabase
        .from('quotations')
        .insert({
          client_name: data.client_name,
          client_phone: data.client_phone || null,
          client_email: data.client_email || null,
          client_note: data.client_note || null,
          job_type: data.job_type,
          event_date: data.event_date || null,
          time_start: data.time_start || null,
          time_end: data.time_end || null,
          location: data.location || null,
          total_price: data.total_price,
          notes: data.notes || null,
          valid_until: data.valid_until || null,
          package_id: data.package_id || null,
          user_id: user.id,
          quotation_number: '', // Generated by trigger
        } as any)
        .select()
        .single();
      
      if (error) throw error;
      return quotation as Quotation;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['quotations'] });
      toast.success('สร้างใบเสนอราคาสำเร็จ');
    },
    onError: (error) => {
      toast.error('ไม่สามารถสร้างใบเสนอราคาได้: ' + error.message);
    },
  });
}

export function useUpdateQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<Quotation> & { id: string }) => {
      const { data: quotation, error } = await supabase
        .from('quotations')
        .update(data)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return quotation as Quotation;
    },
    onSuccess: (quotation) => {
      queryClient.invalidateQueries({ queryKey: ['quotations'] });
      queryClient.invalidateQueries({ queryKey: ['quotation', quotation.id] });
      toast.success('อัพเดทใบเสนอราคาสำเร็จ');
    },
    onError: (error) => {
      toast.error('ไม่สามารถอัพเดทใบเสนอราคาได้: ' + error.message);
    },
  });
}

export function useDeleteQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('quotations')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['quotations'] });
      toast.success('ลบใบเสนอราคาสำเร็จ');
    },
    onError: (error) => {
      toast.error('ไม่สามารถลบใบเสนอราคาได้: ' + error.message);
    },
  });
}

export function useConvertToBooking() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (quotation: Quotation) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Create booking from quotation
      const { data: booking, error: bookingError } = await supabase
        .from('bookings')
        .insert({
          client_name: quotation.client_name,
          client_phone: quotation.client_phone,
          client_email: quotation.client_email,
          client_note: quotation.client_note,
          job_type: quotation.job_type,
          event_date: quotation.event_date || new Date().toISOString().split('T')[0],
          time_start: quotation.time_start,
          time_end: quotation.time_end,
          location: quotation.location,
          total_price: quotation.total_price,
          deposit_amount: 0,
          notes: quotation.notes,
          status: 'draft',
          package_id: quotation.package_id,
          user_id: user.id,
          booking_number: '',
        } as any)
        .select()
        .single();
      
      if (bookingError) throw bookingError;

      // Update quotation status to accepted
      const { error: updateError } = await supabase
        .from('quotations')
        .update({ status: 'accepted' as QuotationStatus })
        .eq('id', quotation.id);
      
      if (updateError) throw updateError;

      return booking;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['quotations'] });
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
      toast.success('แปลงใบเสนอราคาเป็นการจองสำเร็จ');
    },
    onError: (error) => {
      toast.error('ไม่สามารถแปลงเป็นการจองได้: ' + error.message);
    },
  });
}
